const KEY='sequencePlateV4.meals';
const ideal=['Anchor','Expand','Reinforce','Sweet','Drink'];
const types=['Anchor','Expand','Reinforce','Sweet','Drink','Optional','Alcohol','Other'];
let meals=JSON.parse(localStorage.getItem(KEY)||'[]');
let editingId=null;
const $=id=>document.getElementById(id);
function nowLocalParts(){const d=new Date(); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); const iso=d.toISOString(); return {date:iso.slice(0,10), time:iso.slice(11,16), datetime:iso.slice(0,16)}}
function nowLocal(){return nowLocalParts().datetime}
function splitDateTime(dt){ if(!dt) return nowLocalParts(); const clean=dt.includes('T')?dt:nowLocal(); return {date:clean.slice(0,10), time:clean.slice(11,16)||nowLocalParts().time, datetime:clean.slice(0,16)} }
function joinDateTime(){ const p=nowLocalParts(); return `${$('mealDate').value||p.date}T${$('mealTime').value||p.time}`; }
function init(){ const p=nowLocalParts(); $('mealDate').value=p.date; $('mealTime').value=p.time; addDefaultCourses(); bind(); render(); scoreLive(); if('serviceWorker'in navigator) navigator.serviceWorker.register('service-worker.js'); }
function addDefaultCourses(){ $('courses').innerHTML=''; ideal.forEach((t,i)=>addCourse('',t)); }
function addCourse(item='',type='Anchor'){ const wrap=document.createElement('div'); wrap.className='course'; wrap.innerHTML=`<span class="num"></span><input class="item" placeholder="item(s)" value="${escapeHtml(item)}"><select class="type">${types.map(x=>`<option ${x===type?'selected':''}>${x}</option>`).join('')}</select><button class="x" title="Remove">×</button>`; $('courses').appendChild(wrap); renumber(); wrap.querySelector('.x').onclick=()=>{wrap.remove();renumber();scoreLive()}; wrap.querySelectorAll('input,select').forEach(el=>el.oninput=scoreLive); }
function renumber(){[...document.querySelectorAll('.num')].forEach((n,i)=>n.textContent=i+1)}
function bind(){ $('addCourse').onclick=()=>addCourse('', 'Optional'); ['mealName','mealDate','mealTime','context','hungerBefore','satiety','energy','cravings','notes'].forEach(id=>$(id).addEventListener('input',scoreLive)); $('saveMeal').onclick=saveMeal; $('resetForm').onclick=resetForm; $('exportJson').onclick=exportJson; $('exportCsv').onclick=exportCsv; $('importJson').onclick=()=>$('fileInput').click(); $('fileInput').onchange=importJson; $('clearAll').onclick=clearAll; }
function collect(){ return { id:editingId||crypto.randomUUID(), name:$('mealName').value.trim()||$('context').value, datetime:joinDateTime(), context:$('context').value, hungerBefore:+$('hungerBefore').value, courses:[...document.querySelectorAll('.course')].map(c=>({item:c.querySelector('.item').value.trim(), type:c.querySelector('.type').value})), outcomes:{satiety:numOrNull($('satiety').value), energy:numOrNull($('energy').value), cravings:numOrNull($('cravings').value)}, notes:$('notes').value.trim()}; }
function numOrNull(v){return v===''?null:+v}
function calc(meal){ const filled=meal.courses.filter(c=>c.item||c.type); let order=0; filled.forEach((c,i)=>{ const target=ideal[i]; if(c.type===target) order+=20; else if((target==='Sweet'&&['Optional','Alcohol'].includes(c.type))||(target==='Drink'&&c.type==='Other')) order+=12; else if(ideal.includes(c.type)) order+=8; else order+=5; }); order=Math.min(100, Math.round(order/(ideal.length*20)*100)); let outcome=50, count=0; const o=meal.outcomes||{}; if(o.satiety){outcome+= (o.satiety-3)*10; count++} if(o.energy){outcome+= (o.energy-3)*8; count++} if(o.cravings){outcome+= (3-o.cravings)*12; count++} outcome=count?Math.max(0,Math.min(100,Math.round(outcome))):50; const score=Math.round(order*.75 + outcome*.25); return {score,order,outcome}; }
function scoreLive(){ const s=calc(collect()); $('score').textContent=s.score; $('orderBar').style.width=s.order+'%'; $('outcomeBar').style.width=s.outcome+'%'; $('scoreText').textContent=s.score>=90?'Strong structure. Likely supports satiety and decision quality.':s.score>=75?'Good structure. Minor optimization available.':s.score>=60?'Usable structure. Consider anchoring earlier or improving outcomes.':'Low support. Sequence may increase willpower demand.'; }
function saveMeal(){ const meal=collect(); const s=calc(meal); meal.score=s.score; meal.order=s.order; meal.outcome=s.outcome; meal.updatedAt=new Date().toISOString(); const idx=meals.findIndex(m=>m.id===meal.id); if(idx>=0) meals[idx]=meal; else meals.unshift(meal); persist(); resetForm(); render(); }
function resetForm(){ editingId=null; $('saveMeal').textContent='Save Meal'; $('mealName').value=''; { const p=nowLocalParts(); $('mealDate').value=p.date; $('mealTime').value=p.time; } $('context').value='Breakfast'; $('hungerBefore').value='3'; $('satiety').value=''; $('energy').value=''; $('cravings').value=''; $('notes').value=''; addDefaultCourses(); scoreLive(); scrollTo({top:0,behavior:'smooth'}); }
function editMeal(id){ const m=meals.find(x=>x.id===id); if(!m)return; editingId=id; $('saveMeal').textContent='Update Meal'; $('mealName').value=m.name||''; { const p=splitDateTime(m.datetime); $('mealDate').value=p.date; $('mealTime').value=p.time; } $('context').value=m.context||'Breakfast'; $('hungerBefore').value=m.hungerBefore||3; $('satiety').value=m.outcomes?.satiety??''; $('energy').value=m.outcomes?.energy??''; $('cravings').value=m.outcomes?.cravings??''; $('notes').value=m.notes||''; $('courses').innerHTML=''; (m.courses||[]).forEach(c=>addCourse(c.item,c.type)); scoreLive(); scrollTo({top:0,behavior:'smooth'}); }
function duplicateMeal(id){ const m=structuredClone(meals.find(x=>x.id===id)); if(!m)return; m.id=crypto.randomUUID(); m.name=(m.name||'Meal')+' copy'; m.datetime=nowLocal(); const s=calc(m); Object.assign(m,s,{updatedAt:new Date().toISOString()}); meals.unshift(m); persist(); render(); }
function deleteMeal(id){ if(confirm('Delete this meal?')){meals=meals.filter(m=>m.id!==id); persist(); render();} }
function persist(){ localStorage.setItem(KEY,JSON.stringify(meals)); }
function render(){ renderDashboard(); const groups=groupByDay(meals); $('mealGroups').innerHTML=Object.entries(groups).map(([day,items])=>`<div class="day"><div class="day-head"><h3>${day}</h3><strong>${avg(items.map(x=>x.score))}</strong></div>${items.map(mealHtml).join('')}</div>`).join('')||'<p class="hint">No saved meals yet.</p>'; }
function mealHtml(m){ const seq=(m.courses||[]).filter(c=>c.item||c.type).map(c=>`${c.type}: ${escapeHtml(c.item||'—')}`).join(' → '); return `<article class="meal"><h3>${escapeHtml(m.name)} · ${m.score}</h3><p>${fmt(m.datetime)} · ${escapeHtml(m.context)} · hunger ${m.hungerBefore}/5</p><p>${seq}</p>${m.notes?`<p>${escapeHtml(m.notes)}</p>`:''}<div class="meal-actions"><button class="soft" onclick="editMeal('${m.id}')">Edit</button><button class="soft" onclick="duplicateMeal('${m.id}')">Duplicate</button><button class="danger" onclick="deleteMeal('${m.id}')">Delete</button></div></article>`; }
function renderDashboard(){ $('avgScore').textContent=meals.length?avg(meals.map(m=>m.score)):'—'; const cravings=meals.map(m=>m.outcomes?.cravings).filter(Boolean); const sat=meals.map(m=>m.outcomes?.satiety).filter(Boolean); $('avgCraving').textContent=cravings.length?avg(cravings):'—'; $('avgSatiety').textContent=sat.length?avg(sat):'—'; $('bestPattern').textContent=bestPattern(); }
function bestPattern(){ if(meals.length<3)return 'Save at least three meals to identify your best sequence pattern.'; const map={}; meals.forEach(m=>{const p=(m.courses||[]).map(c=>c.type).slice(0,5).join(' → '); if(!map[p])map[p]=[]; map[p].push(m.score);}); const best=Object.entries(map).sort((a,b)=>avg(b[1])-avg(a[1]))[0]; return `Best pattern so far: ${best[0]} · avg ${avg(best[1])}`; }
function groupByDay(list){ return list.reduce((a,m)=>{const d=new Date(m.datetime); const k=d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}); (a[k]??=[]).push(m); return a;},{}); }
function fmt(dt){ return new Date(dt).toLocaleString([], {month:'numeric',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}); }
function avg(arr){return Math.round(arr.reduce((a,b)=>a+b,0)/arr.length)}
function exportJson(){download('sequence-plate-export.json',JSON.stringify(meals,null,2),'application/json')}
function exportCsv(){ const rows=[['name','datetime','context','hungerBefore','score','order','outcome','satiety','energy','cravings','sequence','notes']]; meals.forEach(m=>rows.push([m.name,m.datetime,m.context,m.hungerBefore,m.score,m.order,m.outcome,m.outcomes?.satiety??'',m.outcomes?.energy??'',m.outcomes?.cravings??'',(m.courses||[]).map(c=>`${c.type}: ${c.item}`).join(' -> '),m.notes||''])); download('sequence-plate-export.csv',rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv') }
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function importJson(e){ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{const data=JSON.parse(r.result); if(!Array.isArray(data))throw Error(); meals=data; persist(); render(); alert('Import complete.')}catch{alert('Import failed. Use a Sequence Plate JSON export.')}}; r.readAsText(f); e.target.value=''; }
function clearAll(){ if(confirm('Clear all saved meals from this device?')){meals=[];persist();render();} }
function escapeHtml(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
init();
